### ISSUE TITLE
Unseen and Buried counts;  

### ISSUE THREAD

**Issue by dedu6ka** [yetty/anki-unseen-and-buried-counts#1]
Deleted - wrong issue.

**Comment by Arthur-Milchior** [comment]
Hi,

I'm the author of the change. (Out of curiosity, how do you know so quickly when a change happen to some addon ?)
I did change two things (as a diff can show it; I admit that https://github.com/yetty/anki-unseen-and-buried-counts/commit/47d3e72b94fc1531ca177c68cda62d9b7a99a184 does not really help, it seems I also changed the number of whitespace starting lines. Which was a mistake of my part.

By default, Anki cap to a thousand the number it shows. So you know that you have more than a thousand unseen/buried card. I prefer exact information.

When a deck have children, the unseen/buried count show the total of cards from this very deck plus the number of cards from its descendants. At least, that is what it does on my computer.

Could you please tell me the exact version number of anki that you use ? (Help> About anki), and maybe your OS (but I doubt it changes anything here)
My add-on works for 2.0.47. i didn't test it for 2.1 and I don't intend to look at 2.1, since 2.0 works fine for me. 

when do you have the delay ? With the old add-on ? With the new one ? Always ? How many decks do you have ? I've got 437 decks, and its still efficient. Do you have decks with a lot of subdecks ? (I try to imagine everything which may causes the delay, but I don't have enough information right now)
Finally, what other add-ons do you have ? I can imagine that two add-ons are incompatible, but I can't check every single add-ons.

**Comment by dedu6ka** [comment]
It was my sloppy late night work, sorry for that.  
My feedback is for the add-on "Deck counts NOW LATER".  
Please disregard my Issue.
